name: segmented_button_slide
description: Segmented button with slider indicator. Based on the iOS segmented button but adapted to the Material UI.
version: 2.0.0
homepage: https://github.com/JGeek00/segmented-button-slide

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: